# Generated by Django 5.2.5 on 2025-09-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeropuertos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anumero', models.CharField(max_length=2)),
                ('aaerodescripcion', models.CharField(max_length=20)),
                ('alugar', models.CharField(max_length=50)),
                ('asiglas', models.CharField(max_length=3)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DestPesca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NDESTINO', models.CharField(max_length=2)),
                ('DESTINO', models.CharField(max_length=20)),
                ('REGION', models.CharField(max_length=2)),
                ('LANCHAS', models.IntegerField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuiasPescas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GNGUIA', models.CharField(max_length=2)),
                ('GNOMBREDELGUIA', models.CharField(max_length=20)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LanchasRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REGION', models.CharField(max_length=2)),
                ('SumaDeLANCHAS', models.IntegerField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPesca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MTIPODEPESCA', models.CharField(max_length=1)),
                ('MPESCA', models.CharField(max_length=1)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
