# Generated by Django 5.2.5 on 2025-09-02 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aeropuertos',
            name='anumero',
        ),
    ]
