# Generated by Django 5.2.5 on 2025-09-02 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0002_remove_aeropuertos_anumero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guiaspescas',
            name='GNGUIA',
        ),
    ]
