# Generated by Django 5.2.5 on 2025-09-03 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0003_remove_guiaspescas_gnguia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destpesca',
            name='NDESTINO',
        ),
    ]
