# Generated by Django 5.2.5 on 2025-09-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0004_remove_destpesca_ndestino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destpesca',
            name='LANCHAS',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
