# Generated by Django 5.2.5 on 2025-09-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0005_alter_destpesca_lanchas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destpesca',
            name='REGION',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
