# Generated by Django 5.2.5 on 2025-09-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0006_alter_destpesca_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destpesca',
            name='LANCHAS',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
