# Generated by Django 5.2.5 on 2025-09-03 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0008_alter_destpesca_lanchas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipopesca',
            name='MTIPODEPESCA',
        ),
    ]
