# Generated by Django 5.2.5 on 2025-09-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0009_remove_tipopesca_mtipodepesca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipopesca',
            name='MPESCA',
            field=models.CharField(max_length=10),
        ),
    ]
