# Generated by Django 5.2.5 on 2025-09-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0010_alter_tipopesca_mpesca'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionesPesca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REGIONES', models.CharField(max_length=20)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
