# Generated by Django 5.2.5 on 2025-09-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0011_regionespesca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DESTINO', models.CharField(max_length=20)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
