# Generated by Django 5.2.5 on 2025-09-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0012_destinos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lmarina', models.CharField(max_length=20)),
                ('Nmarina', models.CharField(max_length=50)),
                ('NoficialMarina', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
