# Generated by Django 5.2.5 on 2025-09-06 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0013_marinas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lanchasregion',
            name='REGION',
        ),
        migrations.AddField(
            model_name='lanchasregion',
            name='REGIONES',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainAPI.regionespesca'),
        ),
    ]
