# Generated by Django 5.2.5 on 2025-09-08 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0015_remove_destpesca_region_destpesca_regiones'),
    ]

    operations = [
        migrations.CreateModel(
            name='LugaresHoteles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LugarHotel', models.CharField(max_length=20)),
                ('Direccion', models.CharField(max_length=250)),
                ('Telefono', models.CharField(max_length=20)),
                ('slug', models.SlugField(unique=True)),
                ('Polo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainAPI.destinos')),
            ],
        ),
    ]
