# Generated by Django 5.2.5 on 2025-09-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0016_lugareshoteles'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposHabitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('THABITACION', models.CharField(max_length=10)),
                ('TCANTC', models.IntegerField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
