# Generated by Django 5.2.5 on 2025-09-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0017_tiposhabitaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposhabitaciones',
            name='TCANTC',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
