# Generated by Django 5.2.5 on 2025-09-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0018_alter_tiposhabitaciones_tcantc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TPLANALIM', models.CharField(max_length=3)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
