# Generated by Django 5.2.5 on 2025-09-11 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0019_regimen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('polo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainAPI.destinos')),
            ],
        ),
        migrations.CreateModel(
            name='RentRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Direccioncasa', models.CharField(max_length=70)),
                ('telefonocasa', models.CharField(max_length=10)),
                ('contactocasa', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('municipcasa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainAPI.municipios')),
                ('polocasa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainAPI.destinos')),
            ],
        ),
    ]
