# Generated by Django 5.2.5 on 2025-09-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0020_municipios_rentroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentroom',
            name='contactocasa',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rentroom',
            name='telefonocasa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
