# Generated by Django 5.2.5 on 2025-09-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0021_alter_rentroom_contactocasa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentroom',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
