# Generated by Django 5.2.5 on 2025-09-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0022_alter_rentroom_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nacionalidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
