# Generated by Django 5.2.5 on 2025-09-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0023_nacionalidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrigReservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ONO', models.CharField(max_length=2)),
                ('ONOMBRE', models.CharField(max_length=50)),
                ('OCORREO', models.CharField(max_length=80)),
                ('Onreservai', models.CharField(max_length=2)),
                ('onreservaf', models.CharField(max_length=2)),
                ('ONINICIOCOD', models.IntegerField()),
                ('temporada', models.CharField(max_length=50)),
                ('codini', models.CharField(max_length=50)),
                ('codfin', models.CharField(max_length=50)),
                ('sweetin', models.BooleanField()),
                ('automaticfilemaker', models.BooleanField()),
                ('automaticexcel', models.BooleanField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
