# Generated by Django 5.2.5 on 2025-09-14 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0024_origreservas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='origreservas',
            name='ONO',
        ),
    ]
