# Generated by Django 5.2.5 on 2025-09-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0025_remove_origreservas_ono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origreservas',
            name='OCORREO',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
