# Generated by Django 5.2.5 on 2025-09-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0026_alter_origreservas_ocorreo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposCarros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desctipocarro', models.CharField(max_length=20)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='origreservas',
            name='codfin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='origreservas',
            name='codini',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='origreservas',
            name='temporada',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
