# Generated by Django 5.2.5 on 2025-09-16 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0027_tiposcarros_alter_origreservas_codfin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VuelosDomesticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vdnvuelo', models.CharField(max_length=50)),
                ('vdfvueloi', models.DateField()),
                ('vdfvuelor', models.DateField()),
                ('vddiasemana', models.CharField(choices=[(1, 'Domingo'), (2, 'Lunes'), (3, 'Martes'), (4, 'Miercoles'), (5, 'Jueves'), (6, 'Viernes'), (7, 'Sábado')], max_length=2)),
                ('vdhsalida', models.DateField()),
                ('vdhllegada', models.DateField()),
                ('vdcapacasignadai', models.IntegerField()),
                ('vdpnrasignadoi', models.CharField(max_length=10)),
                ('vdcapacasignadar', models.IntegerField()),
                ('vdpnrasignador', models.CharField(max_length=10)),
                ('slug', models.SlugField(unique=True)),
                ('vddestino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vuelos_destino', to='mainAPI.aeropuertos')),
                ('vdlugardesalida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vuelos_lugar_salida', to='mainAPI.destinos')),
                ('vdpolo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vuelos_polo', to='mainAPI.destinos')),
                ('vdterminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vuelos_terminal', to='mainAPI.aeropuertos')),
            ],
        ),
    ]
