# Generated by Django 5.2.5 on 2025-09-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0028_vuelosdomesticos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelosdomesticos',
            name='vdhllegada',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='vuelosdomesticos',
            name='vdhsalida',
            field=models.TimeField(),
        ),
    ]
