# Generated by Django 5.2.5 on 2025-09-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0029_alter_vuelosdomesticos_vdhllegada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelosdomesticos',
            name='vdfvuelor',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vuelosdomesticos',
            name='vdpnrasignadoi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vuelosdomesticos',
            name='vdpnrasignador',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
