# Generated by Django 5.2.5 on 2025-09-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0030_alter_vuelosdomesticos_vdfvuelor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelosdomesticos',
            name='vddiasemana',
            field=models.CharField(blank=True, choices=[(1, 'Domingo'), (2, 'Lunes'), (3, 'Martes'), (4, 'Miercoles'), (5, 'Jueves'), (6, 'Viernes'), (7, 'Sábado')], max_length=2, null=True),
        ),
    ]
