# Generated by Django 5.2.5 on 2025-09-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0031_alter_vuelosdomesticos_vddiasemana'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OPERADOR', models.CharField(max_length=20)),
                ('IOPERADOR', models.CharField(blank=True, max_length=20, null=True)),
                ('ioperador2', models.CharField(blank=True, max_length=20, null=True)),
                ('OSEGUIMIENTO', models.BooleanField()),
                ('ocodigo', models.BooleanField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vuelosdomesticos',
            name='vdcapacasignadai',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
