# Generated by Django 5.2.5 on 2025-09-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0032_operadores_alter_vuelosdomesticos_vdcapacasignadai'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AGENCIA', models.CharField(max_length=20)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
