# Generated by Django 5.2.5 on 2025-09-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0033_agencias'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatGenerales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NRESERVA', models.CharField(blank=True, max_length=10, null=True)),
                ('NIZQUIERDA', models.CharField(blank=True, max_length=2, null=True)),
                ('RCSOLICITUD', models.IntegerField(blank=True, null=True)),
                ('NDERECHA', models.CharField(blank=True, max_length=6, null=True)),
                ('RORIGENDELARESERVA', models.CharField(blank=True, max_length=2, null=True)),
                ('RCORIGENDELARESERVA', models.IntegerField(blank=True, null=True)),
                ('RCARPETA', models.IntegerField(blank=True, null=True)),
                ('RISERVICIO', models.DateField(blank=True, null=True)),
                ('RFSERVICIO', models.DateField(blank=True, null=True)),
                ('RCUBATUR', models.CharField(blank=True, max_length=10, null=True)),
                ('RHOTEL', models.CharField(blank=True, max_length=4, null=True)),
                ('RNOMBRE', models.CharField(max_length=50)),
                ('RAGENCIA', models.CharField(blank=True, max_length=3, null=True)),
                ('ROPERADOR', models.CharField(blank=True, max_length=3, null=True)),
                ('RCANTPAX', models.IntegerField(blank=True, null=True)),
                ('RCANTPAXPREV', models.IntegerField()),
                ('RESTADODELARESERVA', models.CharField(blank=True, max_length=1, null=True)),
                ('RCOMENTARIO', models.CharField(blank=True, max_length=100, null=True)),
                ('RRECOGIDA', models.CharField(blank=True, max_length=20, null=True)),
                ('RALOJAMIENTO', models.CharField(blank=True, max_length=2, null=True)),
                ('RTIPODEPESCA', models.CharField(blank=True, max_length=1, null=True)),
                ('RIN', models.DateField(blank=True, null=True)),
                ('ROUT', models.DateField(blank=True, null=True)),
                ('RDESTINO', models.CharField(blank=True, max_length=2, null=True)),
                ('RCPAXDESTINO', models.IntegerField(blank=True, null=True)),
                ('RCPAXDESTINOPREV', models.IntegerField(blank=True, null=True)),
                ('RFSOLICITUD', models.DateField(blank=True, null=True)),
                ('REXCLUSIVA', models.BooleanField()),
                ('rinicial', models.IntegerField(blank=True, null=True)),
                ('RULTIMOCLIEN', models.IntegerField(blank=True, null=True)),
                ('dias', models.IntegerField(blank=True, null=True)),
                ('bloqueada', models.BooleanField()),
                ('RCDADOXOPERADOR', models.CharField(blank=True, max_length=50, null=True)),
                ('temporada', models.CharField(blank=True, max_length=11, null=True)),
                ('solicitante', models.CharField(blank=True, max_length=2, null=True)),
                ('modreserva', models.IntegerField(blank=True, null=True)),
                ('modaloj', models.IntegerField(blank=True, null=True)),
                ('modtransf', models.IntegerField(blank=True, null=True)),
                ('modclient', models.IntegerField(blank=True, null=True)),
                ('modocausas', models.IntegerField(blank=True, null=True)),
                ('rcerrada', models.BooleanField()),
                ('rPROTEGIDA', models.BooleanField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
