# Generated by Django 5.2.5 on 2025-09-24 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0034_datgenerales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datgenerales',
            name='RAGENCIA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agencias_reserva', to='mainAPI.agencias'),
        ),
        migrations.AlterField(
            model_name='datgenerales',
            name='RDESTINO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destino_reserva', to='mainAPI.destpesca'),
        ),
        migrations.AlterField(
            model_name='datgenerales',
            name='ROPERADOR',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operador_reserva', to='mainAPI.operadores'),
        ),
        migrations.AlterField(
            model_name='datgenerales',
            name='RORIGENDELARESERVA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orige_reserva', to='mainAPI.origreservas'),
        ),
    ]
